#!/bin/bash
dnf update -y
dnf install -y httpd wget php-fpm php-mysqli php-json php php-devel
dnf install php-mbstring php-xml -y
systemctl start httpd
systemctl enable httpd
systemctl is-enabled httpd
usermod -a -G apache ec2-user
sudo chown -R ec2-user:apache /var/www
systemctl restart httpd
systemctl restart php-fpm
cd /var/www/html
echo "<p><center><h2> Servidor:<i>$HOSTNAME</i></h2></center></p>" >> /var/www/html/index.html
wget https://www.phpmyadmin.net/downloads/phpMyAdmin-latest-all-languages.tar.gz
mkdir phpMyAdmin && tar -xvzf phpMyAdmin-latest-all-languages.tar.gz -C phpMyAdmin --strip-components 1
wget https://wordpress.org/latest.tar.gz
tar -xvzf latest.tar.gz -C ./ --strip-components 1
sudo chmod 2775 /var/www && find /var/www -type d -exec sudo chmod 2775 {} \;
sudo find /var/www -type f -exec sudo chmod 0664 {} \;
